#!/bin/bash

# gShell
# 
# Copyright (C) LiveG. All Rights Reserved.
# 
# https://liveg.tech
# Licensed by the LiveG Open-Source Licence, which can be found at LICENCE.md.

FORCE=false

if [ "$1" == "--force" ]; then
    FORCE=true
fi

if [ $FORCE == false ] && [ -f src/clib/libgslai.so ]; then
    echo "Skipped building of included C libraries because they already exist (run \`$0 --force\` to force a build)"

    exit
fi

echo "Building included C libaries..."

if [ ! -n "$CC" ]; then
    CC=gcc
fi

echo "Using C compiler: $CC"

$CC src/csrc/libgslai.c -o src/clib/libgslai.so -fPIC -shared -ldl

echo "Build complete!"