#!/bin/bash

# gShell
# 
# Copyright (C) LiveG. All Rights Reserved.
# 
# https://liveg.tech
# Licensed by the LiveG Open-Source Licence, which can be found at LICENCE.md.

mkdir -p src/clib
mkdir -p src/cbin

echo "Building included C libaries..."

if [ ! -n "$CC" ]; then
    CC=gcc
fi

echo "Using C compiler: $CC"

$CC src/csrc/libgslai.c -o src/clib/libgslai.so -fPIC -shared -ldl

echo "Building included C executables..."

$CC src/csrc/clset.c -o src/cbin/clset $(pkg-config --cflags --libs x11 xkbcommon)

echo "Build complete!"