#!/bin/bash

# gShell
# 
# Copyright (C) LiveG. All Rights Reserved.
# 
# https://liveg.tech
# Licensed by the LiveG Open-Source Licence, which can be found at LICENCE.md.

./buildclibs

Xephyr +xinerama -ac -screen 1200x800 :1 -nocursor -glamor &

xephyrProcess=$!

DISPLAY=:1.0 npm run gshell -- --in-xephyr $@

kill $xephyrProcess